# Generated by Django 3.1.1 on 2020-10-30 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_score', models.IntegerField(blank=None, choices=[('max_agree', 1), ('med_agree', 2), ('min_agree', 3), ('neutral', 4), ('min_disagree', 5), ('med_disagree', 6), ('max_disagree', 7)])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
