# Generated by Django 3.1.1 on 2020-10-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_scalechoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scalechoice',
            name='choice_score',
            field=models.IntegerField(blank=None, choices=[(1, 'max_agree'), (2, 'med_agree'), (3, 'min_agree'), (4, 'neutral'), (5, 'min_disagree'), (6, 'med_disagree'), (7, 'max_disagree')]),
        ),
    ]
