# Generated by Django 3.0.2 on 2020-10-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
