# Generated by Django 3.1.2 on 2020-10-20 08:39

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0, validators=[books.validators.pages_validator]),
        ),
    ]
