# Generated by Django 3.1.2 on 2020-10-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.FloatField(),
        ),
    ]
