# Generated by Django 3.1.1 on 2020-09-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django101', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
