# Generated by Django 3.0.2 on 2020-08-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=250)),
                ('post_image', models.ImageField(upload_to='blog/images/')),
                ('post_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
